# Generated by Django 2.2.4 on 2021-01-02 06:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trcks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='chacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alw', models.FloatField(blank=True, null=True)),
                ('doa', models.IntegerField(blank=True, null=True)),
                ('total_condemenna', models.IntegerField(blank=True, null=True)),
                ('ascites', models.IntegerField(blank=True, null=True)),
                ('septicemia', models.IntegerField(blank=True, null=True)),
                ('runts_culls', models.IntegerField(blank=True, null=True)),
                ('dermatitis', models.IntegerField(blank=True, null=True)),
                ('others', models.IntegerField(blank=True, null=True)),
                ('gangrene', models.IntegerField(blank=True, null=True)),
                ('whuole_bruises', models.IntegerField(blank=True, null=True)),
                ('peneumodermia', models.IntegerField(blank=True, null=True)),
                ('synovitis_arthritis', models.IntegerField(blank=True, null=True)),
                ('jaundice', models.IntegerField(blank=True, null=True)),
                ('over_scaled', models.IntegerField(blank=True, null=True)),
                ('poor_bleeding', models.IntegerField(blank=True, null=True)),
                ('machine_damage', models.CharField(max_length=20, null=True)),
                ('wing_bruises', models.CharField(max_length=20, null=True)),
                ('wing_broken', models.CharField(max_length=20, null=True)),
                ('wing_dislocation', models.CharField(max_length=20, null=True)),
                ('breast_bruises', models.CharField(max_length=20, null=True)),
                ('breast_skin_lesion', models.CharField(max_length=20, null=True)),
                ('breast_laceration', models.CharField(max_length=20, null=True)),
                ('legs_bruises', models.CharField(max_length=20, null=True)),
                ('legs_scrach', models.CharField(max_length=20, null=True)),
                ('legs_old_injury', models.CharField(max_length=20, null=True)),
                ('legs_fractures', models.CharField(max_length=20, null=True)),
                ('feet_ammonia_burn', models.CharField(max_length=20, null=True)),
                ('feet_broken', models.CharField(max_length=20, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('farms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='first_app.Farm')),
                ('trucks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='first_app.Trcks')),
            ],
        ),
    ]
