# Generated by Django 2.2.4 on 2021-01-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chacks',
            name='feet_broken',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
